name: Debug Session

on:
  workflow_dispatch:
    inputs:
      debug_os:
        type: choice
        description: "Select OS where tmate debug session should run"
        required: false
        default: ubuntu-24.04
        options:
          - ubuntu-24.04
          - macos-14
          - macos-15

jobs:
  # -------------------------------------------------------
  # Setup interactive debug session with tmate
  # -------------------------------------------------------
  debug:
    name: Debug on ${{ github.event.inputs.debug_os }}
    runs-on: ${{ github.event.inputs.debug_os }}
    permissions:
      contents: read

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
        with:
          persist-credentials: false

      - name: 🐞 Setup interactive tmate session (detached)
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113   # v3.24
        with:
          detached: true

      - name: 🧰 Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update -y
            sudo apt-get install -y bats
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install bats-core
          fi

      - name: 🧪 Run Bats tests
        run: |
          echo "Running Bats tests..."
          bats --version
          bats test
